/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'todayCommission' : number,
  'transferOut' : number,
  'transferIn' : number,
  'totalCurrentBalance' : number,
  'lockedDeposit' : number,
}
export interface DepositRecord {
  'timestamp' : bigint,
  'utrNumber' : string,
  'amount' : number,
}
export interface UPIEntry {
  'status' : UPIStatus,
  'totalCommission' : number,
  'todayCommission' : number,
  'upiId' : string,
}
export type UPIStatus = { 'running' : null } |
  { 'online' : null };
export interface _SERVICE {
  'addDeposit' : ActorMethod<[number, string], undefined>,
  'addUpiEntry' : ActorMethod<[string], undefined>,
  'deleteUpiEntry' : ActorMethod<[string], undefined>,
  'getAllUpiEntries' : ActorMethod<[], Array<UPIEntry>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDepositHistory' : ActorMethod<[], Array<DepositRecord>>,
  'updateDashboardStats' : ActorMethod<[DashboardStats], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];