/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UPIStatus = IDL.Variant({
  'running' : IDL.Null,
  'online' : IDL.Null,
});
export const UPIEntry = IDL.Record({
  'status' : UPIStatus,
  'totalCommission' : IDL.Float64,
  'todayCommission' : IDL.Float64,
  'upiId' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'todayCommission' : IDL.Float64,
  'transferOut' : IDL.Float64,
  'transferIn' : IDL.Float64,
  'totalCurrentBalance' : IDL.Float64,
  'lockedDeposit' : IDL.Float64,
});
export const DepositRecord = IDL.Record({
  'timestamp' : IDL.Int,
  'utrNumber' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addDeposit' : IDL.Func([IDL.Float64, IDL.Text], [], []),
  'addUpiEntry' : IDL.Func([IDL.Text], [], []),
  'deleteUpiEntry' : IDL.Func([IDL.Text], [], []),
  'getAllUpiEntries' : IDL.Func([], [IDL.Vec(UPIEntry)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDepositHistory' : IDL.Func([], [IDL.Vec(DepositRecord)], ['query']),
  'updateDashboardStats' : IDL.Func([DashboardStats], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UPIStatus = IDL.Variant({ 'running' : IDL.Null, 'online' : IDL.Null });
  const UPIEntry = IDL.Record({
    'status' : UPIStatus,
    'totalCommission' : IDL.Float64,
    'todayCommission' : IDL.Float64,
    'upiId' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'todayCommission' : IDL.Float64,
    'transferOut' : IDL.Float64,
    'transferIn' : IDL.Float64,
    'totalCurrentBalance' : IDL.Float64,
    'lockedDeposit' : IDL.Float64,
  });
  const DepositRecord = IDL.Record({
    'timestamp' : IDL.Int,
    'utrNumber' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    'addDeposit' : IDL.Func([IDL.Float64, IDL.Text], [], []),
    'addUpiEntry' : IDL.Func([IDL.Text], [], []),
    'deleteUpiEntry' : IDL.Func([IDL.Text], [], []),
    'getAllUpiEntries' : IDL.Func([], [IDL.Vec(UPIEntry)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDepositHistory' : IDL.Func([], [IDL.Vec(DepositRecord)], ['query']),
    'updateDashboardStats' : IDL.Func([DashboardStats], [], []),
  });
};

export const init = ({ IDL }) => { return []; };