/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DepositRecord {
    timestamp: bigint;
    utrNumber: string;
    amount: number;
}
export interface UPIEntry {
    status: UPIStatus;
    totalCommission: number;
    todayCommission: number;
    upiId: string;
}
export interface DashboardStats {
    todayCommission: number;
    transferOut: number;
    transferIn: number;
    totalCurrentBalance: number;
    lockedDeposit: number;
}
export enum UPIStatus {
    running = "running",
    online = "online"
}
export interface backendInterface {
    addDeposit(amount: number, utrNumber: string): Promise<void>;
    addUpiEntry(upiId: string): Promise<void>;
    deleteUpiEntry(upiId: string): Promise<void>;
    getAllUpiEntries(): Promise<Array<UPIEntry>>;
    getDashboardStats(): Promise<DashboardStats>;
    getDepositHistory(): Promise<Array<DepositRecord>>;
    updateDashboardStats(stats: DashboardStats): Promise<void>;
}
import type { UPIEntry as _UPIEntry, UPIStatus as _UPIStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addDeposit(arg0: number, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDeposit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDeposit(arg0, arg1);
            return result;
        }
    }
    async addUpiEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUpiEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUpiEntry(arg0);
            return result;
        }
    }
    async deleteUpiEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUpiEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUpiEntry(arg0);
            return result;
        }
    }
    async getAllUpiEntries(): Promise<Array<UPIEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUpiEntries();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUpiEntries();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getDepositHistory(): Promise<Array<DepositRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepositHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepositHistory();
            return result;
        }
    }
    async updateDashboardStats(arg0: DashboardStats): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDashboardStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDashboardStats(arg0);
            return result;
        }
    }
}
function from_candid_UPIEntry_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UPIEntry): UPIEntry {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_UPIStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UPIStatus): UPIStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _UPIStatus;
    totalCommission: number;
    todayCommission: number;
    upiId: string;
}): {
    status: UPIStatus;
    totalCommission: number;
    todayCommission: number;
    upiId: string;
} {
    return {
        status: from_candid_UPIStatus_n4(_uploadFile, _downloadFile, value.status),
        totalCommission: value.totalCommission,
        todayCommission: value.todayCommission,
        upiId: value.upiId
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    running: null;
} | {
    online: null;
}): UPIStatus {
    return "running" in value ? UPIStatus.running : "online" in value ? UPIStatus.online : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UPIEntry>): Array<UPIEntry> {
    return value.map((x)=>from_candid_UPIEntry_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
